name: dart2_ang5_route2
description: A web app that uses AngularDart Components

environment:
  sdk: '>=2.0.0-dev.51.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+11
  angular_components: ^0.9.0-alpha+11
  angular_router: ^2.0.0-alpha

dev_dependencies:
  angular_test: ^2.0.0-alpha+9
  build_runner: ^0.8.8
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  #mockito: ^2.2.3
  test: ^0.12.30

dependency_overrides:
  # Needed to ensure 0.4.0-alpha+12 (or greater) is not accessed
  # https://github.com/dart-lang/stagehand/issues/506
  #angular_compiler: 0.4.0-alpha+11
